[package]
name = "serde_dynamo"
version = "3.0.3"
authors = ["Bryan Burgers <bryan@burgers.io>"]
edition = "2021"
license = "MIT"
description = "serde serializer/deserializer for DynamoDB items"
readme = "README.md"
documentation = "https://docs.rs/serde_dynamo"
homepage = "https://github.com/zenlist/serde_dynamo"
repository = "https://github.com/zenlist/serde_dynamo"
keywords = ["serde", "rusoto", "dynamodb", "dynamo", "serde_dynamodb"]

[dependencies]
aws-sdk-dynamodb = { version = "0.10", default-features = false }
serde = "1"

[dev-dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde_bytes = "0.11"
serde_derive = "1"
serde_json = "1"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
